name: Test and Deploy

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        #Lint only the packages and not old files
        cd LabTools
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install LaTeX
      run: sudo apt-get install -y texlive-latex-base texlive-science texlive-latex-extra cm-super
    - name: Install LabTools
      run: |
        pip install .
    - name: Test with pytest
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: |
        pip install pytest pytest-cov
        python -m pytest --cov LabTools
        bash <(curl -s https://codecov.io/bash)

  deploy:
    build-n-publish: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Test build with twine
      run: |
        pip install twine
        twine check dist/*
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
